name: Feature Workflow

on:
  pull_request:
    branches:
      - develop
    paths-ignore:
      - '*.md'

env:
  DATABASE_URL: postgres://postgres:mysecretpassword@localhost:5432/notifications

jobs:
  Build:
    name: Test app
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      # ==============================
      - name: Dump context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "${GITHUB_CONTEXT}"
      # ==============================

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Generate .env files
        run: |
          cp .env.example .env

      - name: Read .nvmrc
        run: echo "name=NVMRC::$(cat .nvmrc)" >> $GITHUB_OUTPUT
        id: nvm

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '${{ steps.nvm.outputs.NVMRC }}'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --immutable

      - name: Generate next cache name
        id: next-cache-name
        run: |
          NAME=next-cache-${{ hashFiles('**/yarn.lock') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx', '') }}
          echo "name=$NAME" >> $GITHUB_OUTPUT

      # Based on steps described here - https://nextjs.org/docs/pages/building-your-application/deploying/ci-build-caching#github-actions
      - name: Restore next cache
        id: restore-next-cache
        uses: actions/cache/restore@v3
        with:
          path: ${{ github.workspace }}/.next/cache
          key: ${{ steps.next-cache-name.outputs.name }}
          restore-keys: next-cache-${{ hashFiles('**/yarn.lock') }}-

      - name: Build application
        run: yarn build

      - name: Save next cache
        if: steps.restore-next-cache.outputs.cache-hit != 'true'
        uses: actions/cache/save@v3
        with:
          path: ${{ github.workspace }}/.next/cache
          key: ${{ steps.next-cache-name.outputs.name }}

      - name: Units Tests
        run: yarn jest --ci
      
      - name: Lint files
        run: yarn lint